### ISSUE TITLE
Plugin does not work for gedit 3.14

### ISSUE THREAD

**Issue by maicmarin** [GeorgesStavracas/gedit-markdown#5]
I upgraded to 3.14 and gedit crashed with segmentation fault. Removing the plugin solves the problem.

**Comment by GeorgesStavracas** [comment]
I'll check it out. Oddly enought, it doesn't crash for me.

**Comment by GeorgesStavracas** [comment]
maicmarin: can you provide any stack trace?

Just run gedit in the terminal with the plugin enabled.

**Comment by maicmarin** [comment]
Sorry for the delay... to busy at work...

Here you have:

```
$ gedit
Could not detect FTS supports, disabling Dashboard search
Segmentation fault (core dumped)
$
```

And the trace

```
(gdb) run --no-daemon --verbose
Starting program: /usr/bin/gedit --no-daemon --verbose
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffecc6a700 (LWP 18985)]
[New Thread 0x7fffe693a700 (LWP 18986)]
[New Thread 0x7fffdc76c700 (LWP 18987)]
[New Thread 0x7fffdbd5e700 (LWP 18988)]
[New Thread 0x7fffdb55d700 (LWP 18989)]
[New Thread 0x7fffdad5c700 (LWP 18990)]
[New Thread 0x7fffda55b700 (LWP 18991)]
Could not detect FTS supports, disabling Dashboard search

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff78690a0 in g_menu_model_get_n_items () from /usr/lib/libgio-2.0.so.0
```

Maybe you could thing the problem is the warning about _linux-vdso.so.1_ but, here is the trace with the plug-in removed:

```
(gdb) run --no-daemon --verbose
Starting program: /usr/bin/gedit --no-daemon --verbose
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffecc6a700 (LWP 19173)]
[New Thread 0x7fffe693a700 (LWP 19174)]
[New Thread 0x7fffdc76c700 (LWP 19175)]
[New Thread 0x7fffdbd5e700 (LWP 19176)]
[New Thread 0x7fffdb55d700 (LWP 19177)]
[New Thread 0x7fffdad5c700 (LWP 19178)]
[New Thread 0x7fffda55b700 (LWP 19179)]
Could not detect FTS supports, disabling Dashboard search
[New Thread 0x7fffd96d2700 (LWP 19182)]
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/dashboard/__init__.py", line 54, in _add_tab
    [0].get_children()[0].get_children()[1].hide()
AttributeError: 'Image' object has no attribute 'get_children'
[Thread 0x7fffdc76c700 (LWP 19175) exited]
```

And... after that gedit starts fine.

My box:

Linux miguel 3.17.1-1-ARCH #1 SMP PREEMPT Wed Oct 15 15:04:35 CEST 2014 x86_64 GNU/Linux

**Comment by GeorgesStavracas** [comment]
It seems that it's conflicting with dashboard plugin. I'll check it out.

**Comment by GeorgesStavracas** [comment]
It's really hard to fix it, since I cannot reproduce this issue. Worse, after this all, I believe it's more related to some weird config in you box than anything else.
I get the same stacktrace with Dashboard AND Markdown plugins enabled, and both are working.

Some thoughts on it:
- Clean up the plugins and restart them. The issue continues?
- Clean up you gedit-markdow setup (including ~/.config/gedit-markdown/*), reinstall it and run test again.

I'm sorry I cannot help with it as expected.

**Comment by maicmarin** [comment]
Now is working fine... I disabled all plugins but gedit-markdown and cleaned all hidden files related to gedit (local, config, cache).

Very tanks for your help.

Best,

M
